# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HydrologicalAnalysisTool
                                 A QGIS plugin
 Timeseries analysis of hydrological simulations and observations
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-07-11
        copyright            : (C) 2023 by Sam Murphy / ECMWF
        email                : sam.murphy@ecmwf.int
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HydrologicalAnalysisTool class from file HydrologicalAnalysisTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hydrological_analysis_tool import HydrologicalAnalysisTool
    return HydrologicalAnalysisTool(iface)
